name: drfrank
favicon: null
layout_spectrum: 0.9628091887570918
typography_spectrum: 0.29564526956528425
title: A Slideshow Experiment
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4805908896960318
  lightness: 0.9184926273301244
  saturation: 0.6569702019914985
  rhythmicContrast: 0.017072285525500774
purpose: []
